src/Entity/Texte.php
<?php

namespace App\Entity;

use App\Repository\TexteRepository;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;

/**
 * @ORM\Entity(repositoryClass=TexteRepository::class)
 */
class Texte implements JsonSerializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $position;

    /**
     * @ORM\Column(type="text")
     */
    private $texte_fr;

    /**
     * @ORM\Column(type="text")
     */
    private $texte_en;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getTexteFr(): ?string
    {
        return $this->texte_fr;
    }

    public function setTexteFr(string $texte_fr): self
    {
        $this->texte_fr = $texte_fr;

        return $this;
    }

    public function getTexteEn(): ?string
    {
        return $this->texte_en;
    }

    public function setTexteEn(string $texte_en): self
    {
        $this->texte_en = $texte_en;

        return $this;
    }

	public function jsonSerialize(): mixed
	{
		return [
			'id' => $this->id,
			'position' => $this->position,
			'texte_fr' => $this->texte_fr,
			'texte_en' => $this->texte_en,
		];
	}
}

src/Form/AdminTexteType.php
<?php

namespace App\Form;

use App\Entity\Texte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdminTexteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
			->add('id', HiddenType::class, [
				'mapped' => false
			])
			->add('position', HiddenType::class, [
				'mapped' => false
			])
            ->add('texte_fr', TextareaType::class, [
				'mapped' => false
			])
            ->add('texte_en', TextareaType::class, [
				'mapped' => false
			])
			->add('creer_texte', SubmitType::class)
			->add('modifier_texte', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Texte::class,
        ]);
    }
}

src/Controller/AdminTexteController.php
<?php

namespace App\Controller;

use App\Entity\Texte;
use App\Form\AdminTexteSelectType;
use App\Form\AdminTexteType;
use App\Repository\TexteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdminTexteController extends AbstractController
{
    /**
	 * @Route("/admin/texte", name="admin_texte")
	 */
    public function index(TexteRepository $texteRepository , Request $request, EntityManagerInterface $manager): Response
    {
		$textes = $texteRepository->findAll();

		$position = null;
		$form = $this->createForm(AdminTexteType::class);
		$form->handleRequest($request);

		$form2 = $this->createForm(AdminTexteSelectType::class);
		$form2->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			if ($form->get('creer_texte')->isClicked()) {
				$texte = new Texte();
				$texte->setPosition(count($textes));
			} else if ($form->get('modifier_texte')->isClicked()) {
				$texte = $texteRepository->find($form->get('id')->getData());
				$position = intval($form->get('position')->getData());
			}
			
			$texte->setTexteFr($form->get('texte_fr')->getData());
			$texte->setTexteEn($form->get('texte_en')->getData());
			$manager->persist($texte);
			$manager->flush();
			$textes = $texteRepository->findAll();

			$texte = new Texte();
			$form = $this->createForm(AdminTexteType::class, $texte);
		}

		if ($form2->isSubmitted() && $form2->isValid()) {
			$position = intval($form2->get('position')->getData());

			if ($form2->get('up')->isClicked() && $position != 0) {
				foreach ($textes as $texte) {
					if ($texte->getPosition() == $position) {
						$texte->setPosition($position - 1);
					} else if ($texte->getPosition() == $position - 1) {
						$texte->setPosition($position);
					}
					$manager->persist($texte);
				}
				$position--;
			} else if ($form2->get('down')->isClicked() && $position != count($textes) - 1) {
				foreach ($textes as $texte) {
					if ($texte->getPosition() == $position) {
						$texte->setPosition($position + 1);
					} else if ($texte->getPosition() == $position + 1) {
						$texte->setPosition($position);
					}
					$manager->persist($texte);
				}
				$position++;
			} else if ($form2->get('remove')->isClicked()) {
				$texte = $texteRepository->findOneBy([
					'position' => $position
				]);
				$manager->remove($texte);
				$manager->flush();

				$textesOrder = $texteRepository->findAll();
				$i = 0;
				foreach ($textesOrder as $texte) {
					$texte->setPosition($i);
					$manager->persist($texte);
					
					$i++;
				}
				$position = null;
			}
			
			$manager->flush();
			
			$textes = $texteRepository->findAll();
		}

        return $this->render('admin_texte/index.html.twig', [
            'form' => $form->createView(),
			'form2' => $form2->createView(),
			'textes' => $textes,
			'position' => $position
        ]);
    }
}

templates/admin_texte/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'admin.index.modifier_la_presentation'|trans %}

{% block body %}
	{% include 'menu/_admin.html.twig' %}

	<h5>{{ 'admin.index.modifier_la_presentation'|trans }}</h5>

	{{ form_start(form) }}
		{{ form_label(form.texte_fr, 'admin.texte.texte_en_francais', {'attr': {'class': 'form-label'}}) }}
		{{ form_widget(form.texte_fr, {'attr': {'class': 'form-control'}}) }}
		<br>

		{{ form_label(form.texte_en, 'admin.texte.texte_en_anglais', {'attr': {'class': 'form-label'}}) }}
		{{ form_widget(form.texte_en, {'attr': {'class': 'form-control'}}) }}
		<br>

		{{ form_widget(form.creer_texte, {'label': 'admin.texte.creer_le_texte', 'attr': {'class': 'btn btn-success'}}) }}
		{{ form_widget(form.modifier_texte, {'label': 'admin.texte.modifier_le_texte', 'attr': {'class': 'btn btn-info', 'style':'display:none'}}) }}
	{{ form_end(form) }}

	{{ form_start(form2) }}
		{{ form_widget(form2.up, {'label': 'admin.texte.haut', 'attr': {'class': 'form-control btn btn-success', 'style':'display:none'}}) }}
		{{ form_widget(form2.down, {'label': 'admin.texte.bas', 'attr': {'class': 'form-control btn btn-info', 'style':'display:none'}}) }}
		{{ form_widget(form2.remove, {'label': 'admin.texte.supprimer', 'attr': {'class': 'form-control btn btn-danger', 'style':'display:none'}}) }}
	{{ form_end(form2) }}

	{% set i = 0 %}
	{% for texte in textes %}
		<div id='texte-{{ i }}' class='texte' style='margin: 20px; border: 2px solid black; user-select: none; padding: 20px; border-radius: 10px'>
			{{ texte.texteFr }}
		</div>
		{% set i = i + 1 %}
	{% endfor %}

	<script>
		const textes = {{ textes|json_encode|raw }};

		const admin_texte_texte_fr = document.getElementById('admin_texte_texte_fr');
		const admin_texte_texte_en = document.getElementById('admin_texte_texte_en');

		const position = '{{ position }}';
		if (position != '') {
			document.getElementById('admin_texte_select_position').value = parseInt(position);
			document.getElementById('admin_texte_position').value = parseInt(position);
			document.getElementById('texte-' + position).style.color = 'white';
			document.getElementById('texte-' + position).style.backgroundColor = 'green';
			document.getElementById('texte-' + position).style.borderColor = 'green';

			document.getElementById('admin_texte_id').value = textes[position].id;
			admin_texte_texte_fr.value = textes[position].texte_fr;
			admin_texte_texte_en.value = textes[position].texte_en;

			document.getElementById('admin_texte_modifier_texte').style.display = '';
			document.getElementById('admin_texte_select_up').style.display = '';
			document.getElementById('admin_texte_select_down').style.display = '';
			document.getElementById('admin_texte_select_remove').style.display = '';
		}

		Array.from(document.getElementsByClassName('texte')).forEach(function(texte) {
			texte.addEventListener('click', function(e) {
				Array.from(document.getElementsByClassName('texte')).forEach(function(texte) {
					texte.style.color = 'black';
					texte.style.backgroundColor = 'white',
					texte.style.borderColor = 'black';
				});
				e.target.style.color = 'white';
				e.target.style.backgroundColor = 'green';
				e.target.style.borderColor = 'green';
				document.getElementById('admin_texte_select_position').value = parseInt(e.target.id.split('-')[1]);
				document.getElementById('admin_texte_position').value = parseInt(e.target.id.split('-')[1]);

				document.getElementById('admin_texte_id').value = textes[parseInt(e.target.id.split('-')[1])].id;
				admin_texte_texte_fr.value = textes[parseInt(e.target.id.split('-')[1])].texte_fr;
				admin_texte_texte_en.value = textes[parseInt(e.target.id.split('-')[1])].texte_en;

				document.getElementById('admin_texte_modifier_texte').style.display = '';
				document.getElementById('admin_texte_select_up').style.display = '';
				document.getElementById('admin_texte_select_down').style.display = '';
				document.getElementById('admin_texte_select_remove').style.display = '';
			});
		});
	</script>
{% endblock %}